### ISSUE TITLE
User(Admin) Login/ Registration

### ISSUE THREAD

**Issue by aedean** [aedean/Healthcare-Questionnaire-Application#1]
### User Stories
**All Users**
- Given that I am a user I should be able to log into the application.
- Given that I am a user I should be able to log out the application. 
- Given that I am a user I should be able to add an address to my account. 
- Given that I am a user I should be able to manage my account details and preferences. 

### Objectives
Be able to login in and logout 
Be able to register and edit all details (Basic and address)

### Commands needed: 

- php artisan make:auth
- php artisan make:model -m (Add new migration file)
- php artisan controller:make NerdController --resource (Adds CRUD elements)

### Tasks

**Extend register controller and tables to add the fields**
- [x] Title
- [x] Make name -> firstname
- [x] Lastname
- [x] User Type

_Functions needed_
- [x] Store
- [x] Update
- [x] Edit
- [x] Create
- [x] Destroy
- [x] Show

_Pages needed_
- [x] Create
- [x] Update/ Edit

**Add fields to register view**
- [x] Title - drop down
- [x] Firstname
- [x] Lastname
- [x] User Type

**Add details to user page**
- [x] Name 

**Create an edit user page**
- [x] Add all fields of the user that can be edited
- [x] Identify controller that needs to be used to add edit and update functions
- [x] Ensure it saves all of the edited data

**Create user types controller and model**
_Fields needed_
- [x] User type ID
- [x] User type name

_Function needed_
- [x] Get all current user types
- [x] Get all current user types select html
