### ISSUE TITLE
Patients Login

### ISSUE THREAD

**Issue by aedean** [aedean/Healthcare-Questionnaire-Application#25]
### User Stories
**All Users**

### Objectives
Create patient
Login as patient
Update patient information

### Guide needed: 

- https://www.youtube.com/playlist?list=PLwAKR305CRO9S6KVHMJYqZpjPzGPWuQ7Q

### Tasks
_Login_
- [x] Follow guide to add another login

---

_Patients Functions needed_
- [x] Create
- [x] Update
- [x] Edit
- [x] Destroy
- [x] Store

_Pages needed_
- [x] Create
- [x] Update/ Edit

_Gender Select_
- [x] Add gender selection function
- [x] Add to create and edit
